/* Generated by build.py — which verticals are available. */
window.VERTICALS = {
  "beauty": {
    "brand": "Lumen",
    "tagline": "Makeup, Skincare and Fragrance"
  },
  "lifestyle": {
    "brand": "Posh Street",
    "tagline": "Footwear, Home and Pets"
  },
  "hotels": {
    "brand": "Wayfarer",
    "tagline": "Places worth staying"
  },
  "airlines": {
    "brand": "Meridian Air",
    "tagline": "Direct routes, fifteen cities"
  },
  "banking": {
    "brand": "Northbank",
    "tagline": "Everyday banking, cards and lending"
  },
  "insurance": {
    "brand": "Fairhaven",
    "tagline": "Cover for the things that matter"
  },
  "fintech": {
    "brand": "Loop",
    "tagline": "Money, moved properly"
  },
  "fashion": {
    "brand": "Ashford Lane",
    "tagline": "Womenswear, menswear and footwear"
  },
  "electronics": {
    "brand": "Kestrel",
    "tagline": "Home appliances and technology"
  },
  "telco": {
    "brand": "Vantis",
    "tagline": "Phones, plans and accessories"
  },
  "home": {
    "brand": "Aldgate",
    "tagline": "Furniture and homeware"
  },
  "luxury": {
    "brand": "Beaumont Vale",
    "tagline": "Designer, curated"
  }
};
