/* Generated by build.py — which verticals are available. */
window.VERTICALS = {
  "beauty": {
    "brand": "Lumen",
    "tagline": "Makeup, Skincare and Fragrance"
  },
  "lifestyle": {
    "brand": "Posh Street",
    "tagline": "Footwear, Home and Pets"
  }
};
